### ISSUE TITLE
Weekly/monthly breakdown per package

### ISSUE THREAD

**Issue by gusaiani** [rafaelrinaldi/npm-downloads#1]
This package is quite awesome, @rafaelrinaldi. 
It will certainly be very useful to many people, thank you for building it.

The ability to see trends may make it even more amazing.

Say you want to see how package "imaginary-super-trendy" is really faring on npm.
You may want to run `npm-downloads imaginary-super-trendy --trends`, and get a breakdown of, for instance, the last 6 months and/or the last 4 weeks.

Of course the ability to query the trends more specifically, e.g. 8 weeks, or 20 months, would also come in super handy.

Congrats!

**Comment by rafaelrinaldi** [comment]
That's a really good idea! Thanks for the suggestion.

**Comment by rafaelrinaldi** [comment]
Even though I like this idea I can't see myself adding support for it anytime soon. Feel free to open a PR if you feel like giving it a shot though.
